### ISSUE TITLE
Use § (grave accent) as summon key

### ISSUE THREAD

**Issue by mikefrancis** [soutar/hyperterm-summon#14]
Hey,

Thanks for making this, just what I was looking for coming from iTerm!

Only issue is I use the § key as the system-wide summon key as I have never used it for anything else, but this isn't supported.

Would it be a huge job to get it supported?

**Comment by dcalhoun** [comment]
I believe this ability would fall under the scope of [Electron Accelerator](https://github.com/electron/electron/blob/master/docs/api/accelerator.md). I would recommend opening an issue there.

**Comment by dcalhoun** [comment]
On second glance, it may also be related to [hyperterm-register-shortcut](https://github.com/soutar/hyperterm-register-shortcut). cc/ @soutar

**Comment by mikefrancis** [comment]
Doing a bit of reading and it seems like this is an issue for [hyperterm-register-shortcut](https://github.com/soutar/hyperterm-register-shortcut), will close this one.

**Comment by soutar** [comment]
@mikefrancis I used the exact same key in iTerm but I never managed to make it work for this plugin. 😢  The `globalShortcut` module from Electron is responsible for doing the actual registering of the key (see:  https://github.com/soutar/hyperterm-register-shortcut/blob/master/index.js#L13-L16) so I think we should raise an issue with the Electron?

**Comment by mikefrancis** [comment]
@soutar Already have done, fingers crossed! https://github.com/electron/electron/issues/8208
