### ISSUE TITLE
Mac Menu Bar Error

### ISSUE THREAD

**Issue by chasingSublimity** [soutar/hyperterm-summon#18]
Hola!

When using this plugin, the hyper menu bar disappears. Additionally, the app does not appear in the quick-switch app bar (cmd+tab) nor the Force Quit list. Hyper still functions, however.

Any ideas as to what might be causing this? I'm running the most recent version of Hyper.

Thanks!

EDIT: Well, reading the docs help. Sorry friends. I had `hideDock` set to true, which explains it wasn't showing up in the app bar or quick-switch tab. However, I still think a bug is present, as the menu bar remains nonexistent, even when Hyper is focused.

**Comment by dcalhoun** [comment]
What your are experiencing is a [limitation of macOS and Electron](https://github.com/electron/electron/issues/592), not a bug with hyperterm-summon.

**Comment by chasingSublimity** [comment]
@dcalhoun Roger, thanks for the info!
