### ISSUE TITLE
Hyper terminal hides when out of focus

### ISSUE THREAD

**Issue by derekedelaney** [soutar/hyperterm-summon#26]
- **OS version and name**: 10.12.6 Mac OS
- **Hyper.app version**: 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/derekedelaney/4261849a3e235bf8489fe7683fa5af3d

## Issue

Hyper hides the window if it is not in focus. 
If click anywhere else it hides itself.

http://recordit.co/0CVwzvoJJP
Above is a link to a screen grab where I click on hyper, then click on finder and it goes away.

This only started happening when I upgraded to 1.4.2.

**Comment by dcalhoun** [comment]
Does quitting and restarting Hyper resolve the issue for you? I had issues post-1.4.2 upgrade as well, but restarting resolved them.

**Comment by derekedelaney** [comment]
It doesn't. Is there a way to check what version I'm running?

**Comment by derekedelaney** [comment]
Never mind, I found it. I am running 1.6.1

**Comment by dcalhoun** [comment]
You likely need to set [`hideOnBlur: false`](https://github.com/soutar/hyperterm-summon/tree/1.6.1#options) in your configuration for `hyperterm-summon`. I'm guessing you upgraded from a version prior to this option being added, which is why you have not encountered this before.

**Comment by derekedelaney** [comment]
That did the trick. Thanks!

**Comment by sjdweb** [comment]
I've hit this too. The strange thing is when I cmd+tab back to Hyper I don't see the window. I either have to hit the hotkey or click the dock icon? Is this intended behaviour?

**Comment by dcalhoun** [comment]
@sjdweb Sounds a bit different. We resolved the previous issue above.

Will you open a new issue with steps to reproduce, expect result, and actual result please? Thanks!
