### ISSUE TITLE
Fails to register after plugins are installed

### ISSUE THREAD

**Issue by sheerun** [soutar/hyperterm-summon#3]
When I edit `plugins` section in hyperterm config, then I get "Failed to register" dialog after they reload (after npm install).

I suspect you somehow forget to unregister global shortcut before registering it again. Could you try modifying `register` function so it detects whether it registered global plugin before and try to unregister it first? (instead of doing it in `subscribe`).

**Comment by sheerun** [comment]
#5 seems to fix it completely, thanks!

**Comment by soutar** [comment]
@sheerun Awesome. Glad it's working better for you. I think there's some work to be done around not overriding shortcuts set up by other plugins or by HyperTerm itself but I'm happy for now.
