### ISSUE TITLE
Breaks Hyper on Windows 10

### ISSUE THREAD

**Issue by zacharyrs** [soutar/hyperterm-summon#31]
- [X] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [X] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 (1703)
- **Hyper.app version**: 1.4.8
- **hyperterm-summon version**: 2.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Here we are](https://gist.github.com/zacharyrs/ee1437c2edb98c41378df17fcc77b3aa)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Can;'t  open it.

---

### Steps to Reproduce
1. Add hyperterm-summon to config.
2. If hyper was open, it'll try reload the plugins and give the following error.
![image](https://user-images.githubusercontent.com/10497077/32131335-10bde788-bc08-11e7-8da4-0874966cf600.png)
3. If not, attempt to launch it. It'll work but you can't use any shortcuts, and can't open the menu. On attempt to open the menu, you get the following.
![image](https://user-images.githubusercontent.com/10497077/32131338-23cdd1a8-bc08-11e7-9a19-4667fa841cfb.png)

*NOTE*: I did try without any plugins albeit hyperterm-summon, but still faced the same issue. Also, the exact same config (albeit the shell), works absolutely fine on macOS.

### Expected Result
I expected hyper to work as it did before installing hyperterm-summon.

### Actual Result
Bugs.

**Comment by dcalhoun** [comment]
Thanks for the report. I’m sorry to hear of your issues. I’ll try to take a look sometime this weekend.

**Comment by dcalhoun** [comment]
@zacharyrs I'm running into a few issues publishing a new release, but I'll get one published today. Thanks again!

**Comment by dcalhoun** [comment]
@zacharyrs `hyperterm-summon@2.0.4` should fix this. Please open new issues for any other problems you encounter. Thanks.

**Comment by zacharyrs** [comment]
Sweet! 

Thanks a bunch for the quick fix!
