### ISSUE TITLE
Unmet dependency electron

### ISSUE THREAD

**Issue by mrgrauel** [soutar/hyperterm-summon#40]
- **OS version and name**: macOS 10.13.4
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **hyperterm-summon version**: hyperterm-summon (2.0.8)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mrgrauel/ee110293d776c639a914a6d2c920019a
- **Relevant information from devtools**: N/A

---

## Issue
* After Update of the plugins hyper also show unmet peer dependency for hyperterm-summon electron

### Steps to Reproduce
1. open hyper
1. update plugins and wait for the notifications

### Expected Result
* all dependencies are resolved

### Actual Result
* missing electron dependency

**Comment by dcalhoun** [comment]
1. You replied "N/A" for "Relevant information from devtools". Was there a specific error message that you can screenshot or copy/paste?
1. When you say "update plugins and wait for the notifications" is this from the "Plugins > Update" menu item or the auto-update that occurs every 5 hours?

**Comment by dcalhoun** [comment]
Thank you for the additional information, @accessd. I'll prepare a fix now.

**Comment by dcalhoun** [comment]
@mrgrauel @accessd please let me know if this is resolved for you in the `hyperterm-summon@2.0.9` release.

**Comment by accessd** [comment]
It's resolved! Thanks for quick fix!

**Comment by mrgrauel** [comment]
Resolved! Thanks
