### ISSUE TITLE
mac: cant set 'alt+@' as hotkey

### ISSUE THREAD

**Issue by HanneMaes** [soutar/hyperterm-summon#42]
Hi
I use macOS and would like to set 'alt+@' as a hotkey, but that key combo writes a '•'.
Any ideas how I can set 'alt+@' as a hotkey?
Thanks

**Comment by dcalhoun** [comment]
Please read about [Electron Accelerator](https://github.com/electron/electron/blob/master/docs/api/accelerator.md). It's likely something like the following.

```js
module.exports = {
  config: {
    summon: {
      hotkey: 'Alt+Shift+2'
    }
  },
  plugins: [
    'hyperterm-summon'
  ]
}
```
