### ISSUE TITLE
Can't set § as hotkey (Key to the left of 1 on mac)

### ISSUE THREAD

**Issue by crumb1e** [soutar/hyperterm-summon#44]
- [x] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [x] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra
- **Hyper.app version**: 2.0.0 Stable
- **hyperterm-summon version**: 2.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/crumb1e/6b7055f6f8a13eb4b323792ff7faac23
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A

---

## Issue
I'd like to use the `§` key as my hotkey, but I am getting js errors when I try to save my config.

### Steps to Reproduce
1. Set hotkey as `§`
2. Try to save

### Expected Result
My hotkey is now `§`

### Actual Result
hyperterm-summon shouted at me

**Comment by dcalhoun** [comment]
It's difficult to know for sure, as your report of "hyperterm-summon shouted at me" does not provide much information, but my best guess is that `§` is [not a valid Accelerator key code](https://github.com/electron/electron/blob/master/docs/api/accelerator.md#available-key-codes).

Please try using a different key code. If you continue to have issues, please post again letting me know. Thanks.
