### ISSUE TITLE
Unable to summon hyper without first manually opening an instance of it

### ISSUE THREAD

**Issue by jcklpe** [soutar/hyperterm-summon#46]
- [x] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [x] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: Canary 2
- **hyperterm-summon version**: latest
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:https://gist.github.com/jcklpe/2770325dbcb56b9e6c5d4c41e04e1d46
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 

---

### Steps to Reproduce
1. Start up computer
2. hit hotkey for hyperterm-summon

### Expected Result
hyper.js starts

### Actual Result
hyper doesn't start. 

**I don't actually know if this is an issue:** Is it even possible to assign a global hotkey to activate an electron app that hasn't yet been started? I assume not. This seems to me like it is probably within the parameters of expected behavior. But I was asked to make a ticket so I did. I went ahead and made an AutoHotkey macro to summon hyper anyway, and the hyper-summon plugin allows me to minimize and and summon it once it's open.

**Comment by dcalhoun** [comment]
Thank you for opening this separate issue, it helps keep threads focused.

From my brief [research](https://stackoverflow.com/a/38554140/378228), I believe you are correct that this is not possible. Electron must be running for it to register a global shortcut.

Happy to hear that you have a work around for now. If you investigate further and find a way to accomplish this, let me know! In the meantime, I'm going to close this issue.

Thanks again.

**Comment by jcklpe** [comment]
For future Windows users who might face this issue here's some info on the AHK solution. 

1. Install AHK
2. write a file that contains the following config. 
`
^+.:: ; ctrl+shift+. to launch hyper.js
Run C:\Users\{{YOUR USERNAME}}\AppData\Local\hyper\app-2.0.0\Hyper.exe
Return
`
3. Hit the win key and type `run` to open the windows runner. 
4. type `shell:startup` to open the Windows shell startup folder. 
5. Place the file.ahk in the folder. Now that ahk script will always register itself at start time.
