### ISSUE TITLE
use hotkey to toggle back to previous app/window

### ISSUE THREAD

**Issue by wkentdag** [soutar/hyperterm-summon#7]
After hitting the hotkey to bring up my terminal, the next thing I usually do (maybe after entering some commands) is switch right back to the previous app. Would be handy to use the same hotkey to toggle back and forth. If you're open to this feature I'd be happy to open a PR 😄

**Comment by soutar** [comment]
@wkentdag Absolutely, this is how I use the hotkey 99% of the time. If you're on Mac OS this should already be implemented (https://github.com/soutar/hyperterm-summon/blob/master/index.js#L18), but if it's not working for you then a PR would be awesome

**Comment by wkentdag** [comment]
Oh wow, you're right! I didn't realize because I usually have all my apps (including hyperterm) full screen - it doesn't appear to work with a full screen app, but then again I haven't been able to find *any* hotkey/visor that works with fullscreen apps on the latest mac OS 😩

**Comment by wkentdag** [comment]
going to close the issue since the feature is already in here, but I'm going to investigate the full screen app thing and might be back with a PR soon. cheers!

**Comment by soutar** [comment]
My gut tells me that might need to be implemented upstream in Electron but
if you solve it I'll merge it! Thanks for raising this anyway, it's good to
be aware of any limitations. I'll probably add something to the readme when
I get a chance.
