### ISSUE TITLE
hideOnBlur doesn't work on Linux

### ISSUE THREAD

**Issue by mwoz123** [soutar/hyperterm-summon#72]
- [x] I am on the [latest](https://github.com/soutar/hyperterm-summon/releases/latest) hyperterm-summon version
- [X] I have searched the [issues](https://github.com/soutar/hyperterm-summon/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:   Ubuntu 20.04.3 LTS
- **Hyper.app version**:  3.1.2
- **hyperterm-summon version**: 2.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mwoz123/337e3a4a0ab3dff916878701ac6d5e4a
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A

---

## Issue

`hideOnBlur ` setting is ignored on Linux. 
It doesn't matter if it is set to `false`, `true` or configuration key-value pair doesnt'  exist - Hyper term window is always hidden after losing focus (alt-tab or mouse click on different window).

### Steps to Reproduce

1. set `hideOnBlur: false,` in `.hyper.js` 
2. wait until config is reloaded, quit hyper
3. start hyper again
3. alt+tab or click on another window 

### Expected Result

Hyper term window should still be visible, might be hover under another window

### Actual Result
Hyper term window is hidden - can be restored with hotkey, but should be still visible

### References: 
might be related to: https://github.com/soutar/hyperterm-summon/issues/56 or https://github.com/soutar/hyperterm-summon/pull/59

**Comment by dcalhoun** [comment]
Thanks for the report. I do agree with you that this is related to the changes made in #59, as it [explicitly disabled](https://github.com/soutar/hyperterm-summon/commit/d8daa14b4b1c48e4f5ccf199154619275df4beef#diff-66be4c8a3d65769cf62944fbe0ddc02b939524cec863d544bffc4b74ca31f4ceR22) support for `hideOnBlur`. 

Unfortunately, I do not have an Ubuntu environment to test the plugins against and I do not believe I will have time to debug it soon. If you are willing, you could [setup hyperterm-summon to run as a "local" plugin](https://hyper.is/#extensions-module-loading), so that you could modify the source and see the results in your local Hyper.

**Comment by mwoz123** [comment]
I can test using Ubuntu 20.04 KDE and Gnome, 

I did quick tests with hyper 3.1.3. and change in `app.js`:
```
 - if (!config.hideOnBlur && process.platform !== 'linux') {
 +  if (!config.hideOnBlur) {
```
and it blur worked fine. Was it an Electron issue?

Any particular scenarios I should test ?

**Comment by dcalhoun** [comment]
> I did quick tests with hyper 3.1.3. and change in `app.js`:
> 
> ```
>  - if (!config.hideOnBlur && process.platform !== 'linux') {
>  +  if (!config.hideOnBlur) {
> ```
> 
> and didn' spot any issues with blur nor hotkey. Was it an Electron issue?

@mwoz123 are you implying this change _fixed_ `hideOnBlur` for Linux? 

> Any particular scenarios I should test ?

My recommendation would be to verify the issues reported in https://github.com/soutar/hyperterm-summon/issues/56 no longer occur. My understanding of https://github.com/soutar/hyperterm-summon/issues/56 is that interacting with the task bar broke summoning Hyper with a hotkey. Thank you for investigating this! 🙇🏻

**Comment by mwoz123** [comment]
my test results . Env: 
```
Operating System: Ubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
```
Config:
```js
        summon: {
            hideDock: false,
            hotkey: 'Ctrl+.'
        }
```

1. hyper visible, active, taskbar icon is visible - clicked on taskbar hyper icon -> hyper is minimized to taskbar, icon is visible in taskbar
2. hyper not visible, minimalized to taskbar - clicked on taskbar hyper icon -> hyper is restored, active, hyper icon is active and visible in taskbar
3. hyper visible, active, icon is visible in taskbar - hotkey pressed - hides hypper, no icon in taskbar visible
4. hyper hidden with hotkey (icon not visible in taskbar) - hotkey pressed -  hyper is visible and active 
5. hyper visible, not active (another non-hyper window is active) - hotkey pressed - hyper icon is shown, hyper is active
6. hyper hidden by clicking on active taskbar hyper icon -> hyper hotkey -> hyper is restored, active
7. hyper is visible -> alt+tab -> hyper window is visible, is visible in taskbar but not active 
8. hyper hidden by hotkey - no ability to restore without hotkey as it's not visible in taksbar - well but as you hide it with hotkey you can restore it with hotkey

Losing focus on hyper doesn't hide it in none of the scenarios 

exaclty same results for :

```js
      summon: {
          hideDock: false,
          hideOnBlur: false,
          hotkey: 'Ctrl+.'
},
```
I didn't spot 'false' was default for hideOnBluer :/


Config: 
```js
        summon: {
          hideDock: false,
          hideOnBlur: true,
          hotkey: 'Ctrl+.'
},
```


10. hyper is visible, active -> alt +tab -> hyper window is hidden, is also hidden from taskbar
11. hyper is not visible in taskbar, nor its window is visible-> hotkey -> hyper is visible, active, visible in taskbar
12. hyper is visible, active-> minimalizing by clicking on taskbar icon -> hyper is visible, visible in taskbar
13. hyper is minimalized to taskbar -> clicking on other taskbar icon doesn't hide it from taksbar

IMHO based on above I'd say `hideOnBlur` it's usable in linux (with above change). 

What you think guys ? Do you need any more tests ?

**Comment by mwoz123** [comment]
If I understand correctly #56, my sceniorios 3. 4. 5.(!) 6. 8. prove it works :
- not only if you hide it prior to switching to another application 
- or Hyper is visible in the taskbar and focused.

**Comment by mwoz123** [comment]
@dcalhoun test passed. PR #75 ;)
