### ISSUE TITLE
Mac Desktop Bug

### ISSUE THREAD

**Issue by acondiff** [soutar/hyperterm-summon#8]
If HyperTerm is on another desktop or in fullscreen, there are problems returning to the previous application. If it is on another desktop it simply hides the window but does not return to the original application. If HyperTerm is fullscreened, the first time it goes to HyperTerm in its fullscreen desktop, pressing it again just hides the Hyperterm UI but it retains it's fullscreen desktop (so it just displays a dark gray screen). It also stays on that desktop and doesn't return to the original app.

**Comment by dcalhoun** [comment]
I've run into the fullscreen issue as well. One additional note, when using the hyperterm-summon hotkey while Hyper.app is fullscreen, the Hyper.app UI will "hide" before sliding out of the way to focus on the previous app. [This is a bit jarring.](http://quick.as/39xdtozdo) Would it be possible to disable the actual "hiding" of the window when the window is fullscreen (i.e. – it only loses focus and slides out of the way)?

**Comment by dcalhoun** [comment]
From my recent testing, this is no longer an issue. Please let me know if you experience otherwise.
